name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - hotfix/*
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Install .NET SDK 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install .NET Core SDK (global.json)
        uses: actions/setup-dotnet@v1
        with:
            include-prerelease: 'true'

      - name: Run Cake script
        uses: cake-build/cake-action@v1
        with:
          target: Run-Integration-Tests
          cake-version: tool-manifest

      - name: Validate Integration Tests
        uses: cake-build/cake-action@master
        with:
          script-path: tests/integration/Cake.Common/Build/GitHubActions/ValidateGitHubActionsProvider.cake
          cake-version: tool-manifest

